name: K6 Load Test

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  k6-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run k6 test
        uses: grafana/k6-action@v0.3.0
        with:
          filename: k6/script.js
          flags: --out cloud
          token: ${{ secrets.GRAFANA_CLOUD_TOKEN }}
